### ISSUE TITLE
Python Code

### ISSUE THREAD

**Issue by cyouh95** [beckyteper/intro-data-capstone-biodiversity#1]
Hey there, could you also submit your python code in addition to the presentation slides? You can save your iPython notebook as a “.py” file using `File > Download as > Python (.py)`. Thanks!

**Comment by beckyteper** [comment]
Hi, I completed the project on the codeacademy.com website. How do I download my python code from the website to submit?

**Comment by beckyteper** [comment]
I have resubmitted with the code.
